Integrationtests for existing ls bus headers
modelica/fmi-ls-bus pull request #149
Opened 2024-03-19 08:58 UTC by emvahle

This pull request contains the infrastructure needed to automatically/manually run tests on the repository's header files. The files include:
- Code and header files for tests
- Workflow files for the corresponding actions
- A ReadMe.txt with an explanation for the testing mechanism
- File fmi3LsBusPlatformTypes.h
- Existing workflow file [build-ls-bus.yml](https://github.com/emvahle/fmi-ls-bus/blob/main/.github/workflows/build-ls-bus.yml) has been adjusted to exclude the new tests directory in main build

2024-03-19 11:34 UTC, pmai requested changes
I think some changes are needed to properly integrate this. The shipping of the headers as part of the artefact should likely first be handled in a separate PR, as it is unrelated.

2024-03-19 11:34 UTC, pmai commented on .github/workflows/build-ls-bus.yml
> +      run: tar --exclude=headers/tests/* -c headers -C docs images examples | tar xfC - build
This seems erroneous, the current step does already not include headers, so why is there a need to now include headers but exclude tests? If headers should be included in the built artefact, this should be handled in a separate step/call and PR, and the name of the step should match.

BTW the exclude syntax should not rely on globbing, but rather be `--exclude=headers/tests`, which will be more reliable and excludes the empty directory.

2024-03-19 11:34 UTC, pmai commented on headers/fmi3PlatformTypes.h
This should not be added to this repo, as it is a copy of the FMI release content. Neither should it be shipped as part of the LS, causing potential conflicts, nor should it be held in the repo just because it is needed for the CI workflows. If the workflow needs it, then a relevant copy should be checked out in the CI workflow.

2024-03-19 11:34 UTC, pmai commented on headers/tests/README.md
Since the tests are just internal quality checks, they should not reside in the headers directory, which contains artefacts that are supposed to be shipped with the LS. e.g. better place at root level of the repo.

2024-03-19 11:34 UTC, pmai commented on .github/workflows/run-header-tests-Debug.yml
It is unclear to me why the tests are run with both Debug and Release modes in any case, given that we do not ship software, but only use this CI for internal quality checks.

And even if we for some reason wanted to run both modes, this should be combined in one workflow, as everything can easily be built and run from separate build directories, no need to wait for vm setup etc. multiple times.

I think it would rather be more important to run the tests with more enable pedantic check flags for the compiler/s in question (or even with multiple compilers), as this is more likely to result in valid quality feedback for headers.

2024-03-19 11:34 UTC, pmai commented on .github/workflows/build-ls-bus.yml
> +
```suggestion
```

No unrelated whitespace changes that make the file whitespace unregular.

2024-03-20 08:30 UTC, emvahle commented
> I think some changes are needed to properly integrate this. The shipping of the headers as part of the artefact should likely first be handled in a separate PR, as it is unrelated.

Hello Pierre, thank you for your feedback. We will have a look into it and refine the pull request.

2024-03-26 14:55 UTC, pmai approved these changes
See proposed changes, otherwise looks fine

2024-03-26 14:55 UTC, pmai commented on tests/CMakeLists.txt
> +  ${CMAKE_CURRENT_SOURCE_DIR}/../headers)
```suggestion
  ${CMAKE_CURRENT_SOURCE_DIR}/../fmi-standard/headers
  ${CMAKE_CURRENT_SOURCE_DIR}/../headers)
```

2024-03-26 14:55 UTC, pmai commented on .github/workflows/run-header-tests.yml
> +        cp $GITHUB_WORKSPACE/fmi-standard/headers/fmi3PlatformTypes.h $GITHUB_WORKSPACE/headers
```suggestion
```

Wouldn't it be simpler to just have the proper include paths in CMakeLists.txt? See proposal below.

2024-03-27 12:04 UTC, merged