Fixed issue 24
modelica/fmi-ls-bus pull request #39
Opened 2023-06-02 11:39 UTC by bmenne-dspace

Fixed issue "Layered Standard Manifest File is missing for fmi-ls-bus"

2023-06-06 08:18 UTC, PTaeuberDS approved these changes
Looks good to me

2023-06-06 08:18 UTC, PTaeuberDS commented on docs/examples/fmi_ls_bus_manifest_example.xml
> +	fmi-ls:fmi-ls-description="Layered Standard for Bus"/>
I would prefer "Layered Standard for Network Communication" as the official name of the LS...
However, this is a description field and is probably displayed in the importing tool. Therefore, it should provide a little more information about the contents of this layered standard. I will create an issue for that here and also in the fmi-ls-xcp repo.

2023-06-13 08:02 UTC, bmenne-dspace commented on docs/examples/fmi_ls_bus_manifest_example.xml
> +	fmi-ls:fmi-ls-description="Layered Standard for Bus"/>
@PTaeuberDS sounds good; I will fix that

2023-06-14 06:17 UTC, andreas-junghanns requested changes
I think we should state the location of the manifest file within the FMU here in this standard as well.

2023-06-14 06:43 UTC, bmenne-dspace commented
> I think we should state the location of the manifest file within the FMU here in this standard as well.

I

> I think we should state the location of the manifest file within the FMU here in this standard as well.

@andreas-junghanns Yes you are right, I will fix it and push the changes

2023-06-14 12:45 UTC, andreas-junghanns approved these changes

2023-06-14 12:47 UTC, merged