Update Low Cut Section
modelica/fmi-ls-bus pull request #9
Opened 2023-02-06 17:26 UTC by PTaeuberDS

This pull request is an update on the Low Cut section (Chapter 4).

Sections 4.1 - 4.5 are ready for a first review.
Section 4.7 (CAN specific section) is also filled with content but still under construction. Please keep that in mind while reading.

From our side this PR can be merged. Our next PRs will be more fine-grained.

2023-02-07 07:37 UTC, andreas-junghanns requested changes
The language and consistent formatting requires significant improvements.
Maybe we can reduce some of the explanations and rely on the reader knowing FMI 3.0?
I am a bit overwhelmed by the amount of text...

2023-02-08 12:47 UTC, chrbertsch approved these changes

2023-02-08 12:48 UTC, chrbertsch reviewed
Let's merge this great improvement soon, and improve in new PRs

2023-02-08 18:42 UTC, andreas-junghanns approved these changes

2023-02-09 09:26 UTC, merged